# Pre-commit:  A framework for managing and maintaining multi-language pre-commit hooks.
# Pre-commit Website: https://pre-commit.com/
repos:
  - repo: local
    hooks:
      - id: prettier
        name: prettier
        description: Prettier is an opinionated code formatter.
        language: system
        entry: prettier --write --ignore-unknown
        types: [text]
      - id: golangci-lint-full
        name: golangci-lint-full
        description:
          Fast linters runner for Go. Runs on all files in the repo. Use this
          hook if you use pre-commit in CI.
        entry: golangci-lint run --fix
        types: [go]
        language: golang
        require_serial: true
        pass_filenames: false
